package com.tugambeta.model;
// Generated 28/11/2016 05:08:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;


/**
 * EstadisticaTorneo generated by hbm2java
 */


public class EstadisticaTorneo  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String pais;
     private Set<EstadisticaPartido> estadisticaPartidos = new HashSet<EstadisticaPartido>(0);

    public EstadisticaTorneo() {
    }

	
    public EstadisticaTorneo(String nombre, String pais) {
        this.nombre = nombre;
        this.pais = pais;
    }
    public EstadisticaTorneo(String nombre, String pais, Set<EstadisticaPartido> estadisticaPartidos) {
       this.nombre = nombre;
       this.pais = pais;
       this.estadisticaPartidos = estadisticaPartidos;
    }
   

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }


    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }

    public Set<EstadisticaPartido> getEstadisticaPartidos() {
        return this.estadisticaPartidos;
    }
    
    public void setEstadisticaPartidos(Set<EstadisticaPartido> estadisticaPartidos) {
        this.estadisticaPartidos = estadisticaPartidos;
    }




}


