package com.tugambeta.model;
// Generated 28/11/2016 05:08:27 PM by Hibernate Tools 4.3.1



/**
 * EstadisticaEquipo generated by hbm2java
 */

public class EstadisticaEquipo  implements java.io.Serializable {


     private Integer id;
     private String nombre;

    public EstadisticaEquipo() {
    }

    public EstadisticaEquipo(String nombre) {
       this.nombre = nombre;
    }
   



    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }


    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


