package com.tugambeta.model;
// Generated 28/11/2016 05:08:27 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;


/**
 * EstadisticaPartido generated by hbm2java
 */


public class EstadisticaPartido implements Serializable {

    private Integer id;
    private EstadisticaTorneo estadisticaTorneo;
    private String local;
    private int goleslocal;
    private String visita;
    private int golesvisita;
    private Date fecha;
    private String jornada;
    private String estadio;

    private String fechaCadena;
    private String torneo;

    public EstadisticaPartido() {
    }

    public EstadisticaPartido(EstadisticaTorneo estadisticaTorneo, String local, int goleslocal, String visita, int golesvisita, Date fecha, String jornada, String estadio) {
        this.estadisticaTorneo = estadisticaTorneo;
        this.local = local;
        this.goleslocal = goleslocal;
        this.visita = visita;
        this.golesvisita = golesvisita;
        this.fecha = fecha;
        this.jornada = jornada;
        this.estadio = estadio;
    }


    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    public EstadisticaTorneo getEstadisticaTorneo() {
        return this.estadisticaTorneo;
    }

    public void setEstadisticaTorneo(EstadisticaTorneo estadisticaTorneo) {
        this.estadisticaTorneo = estadisticaTorneo;
    }

    public String getLocal() {
        return this.local;
    }

    public void setLocal(String local) {
        this.local = local;
    }


    public int getGoleslocal() {
        return this.goleslocal;
    }

    public void setGoleslocal(int goleslocal) {
        this.goleslocal = goleslocal;
    }


    public String getVisita() {
        return this.visita;
    }

    public void setVisita(String visita) {
        this.visita = visita;
    }

    public int getGolesvisita() {
        return this.golesvisita;
    }

    public void setGolesvisita(int golesvisita) {
        this.golesvisita = golesvisita;
    }


    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * @return the jornada
     */

    public String getJornada() {
        return jornada;
    }

    /**
     * @param jornada the jornada to set
     */
    public void setJornada(String jornada) {
        this.jornada = jornada;
    }

    /**
     * @return the estadio
     */

    public String getEstadio() {
        return estadio;
    }

    /**
     * @param estadio the estadio to set
     */
    public void setEstadio(String estadio) {
        this.estadio = estadio;
    }

    /**
     * @return the torneo
     */

    public String getTorneo() {
        return torneo;
    }

    /**
     * @param torneo the torneo to set
     */
    public void setTorneo(String torneo) {
        this.torneo = torneo;
    }

    /**
     * @return the fechaCadena
     */

    public String getFechaCadena() {
        return fechaCadena;
    }

    /**
     * @param fechaCadena the fechaCadena to set
     */
    public void setFechaCadena(String fechaCadena) {
        this.fechaCadena = fechaCadena;
    }

}
