package com.tugambeta.model;
// Generated 5/11/2016 06:03:56 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Jugadorresultados generated by hbm2java
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Jugadorresultados  implements java.io.Serializable {


    private Integer idjugadorResultados;
    private Jugador jugador;
    private Partidos partidos;
    private Quiniela quiniela;
    private String  resultado;


    public Jugadorresultados() {
    }

    public Jugadorresultados(Jugador jugador, Partidos partidos, Quiniela quiniela, String resultado) {
        this.jugador = jugador;
        this.partidos = partidos;
        this.quiniela = quiniela;
        this.resultado = resultado;
    }


    public Integer getIdjugadorResultados() {
        return this.idjugadorResultados;
    }

    public void setIdjugadorResultados(Integer idjugadorResultados) {
        this.idjugadorResultados = idjugadorResultados;
    }


    public Jugador getJugador() {
        return this.jugador;
    }

    public void setJugador(Jugador jugador) {
        this.jugador = jugador;
    }


    public Partidos getPartidos() {
        return this.partidos;
    }

    public void setPartidos(Partidos partidos) {
        this.partidos = partidos;
    }


    public Quiniela getQuiniela() {
        return this.quiniela;
    }

    public void setQuiniela(Quiniela quiniela) {
        this.quiniela = quiniela;
    }



    public String getResultado() {
        return this.resultado;
    }

    public void setResultado(String resultado) {
        this.resultado = resultado;
    }




}




