package com.tugambeta.model;
// Generated 5/11/2016 06:03:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;



/**
 * Jugador generated by hbm2java
 */
public class Jugador  implements java.io.Serializable {


     private Integer idjugar;
     private Quiniela quiniela;
     private Users users;
     private String jugador;
     private String codigo;
     private int aciertos;
     private Set<Jugadorresultados> jugadorresultadoses = new HashSet<Jugadorresultados>(0);

    public Jugador() {
    }

	
    public Jugador(Quiniela quiniela, Users users, String jugador, String codigo, int aciertos) {
        this.quiniela = quiniela;
        this.users = users;
        this.jugador = jugador;
        this.codigo = codigo;
        this.aciertos = aciertos;
    }
    public Jugador(Quiniela quiniela, Users users, String jugador, String codigo, int aciertos, Set<Jugadorresultados> jugadorresultadoses) {
       this.quiniela = quiniela;
       this.users = users;
       this.jugador = jugador;
       this.codigo = codigo;
       this.aciertos = aciertos;
       this.jugadorresultadoses = jugadorresultadoses;
    }

    public Integer getIdjugar() {
        return this.idjugar;
    }
    
    public void setIdjugar(Integer idjugar) {
        this.idjugar = idjugar;
    }


    public Quiniela getQuiniela() {
        return this.quiniela;
    }
    
    public void setQuiniela(Quiniela quiniela) {
        this.quiniela = quiniela;
    }


    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    public String getJugador() {
        return this.jugador;
    }
    
    public void setJugador(String jugador) {
        this.jugador = jugador;
    }


    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }


    public int getAciertos() {
        return this.aciertos;
    }
    
    public void setAciertos(int aciertos) {
        this.aciertos = aciertos;
    }


    public Set<Jugadorresultados> getJugadorresultadoses() {
        return this.jugadorresultadoses;
    }
    
    public void setJugadorresultadoses(Set<Jugadorresultados> jugadorresultadoses) {
        this.jugadorresultadoses = jugadorresultadoses;
    }




}


