package com.tugambeta.model;
// Generated 6/11/2016 12:41:24 PM by Hibernate Tools 4.3.1




/**
 * Liga generated by hbm2java
 */

public class Liga  implements java.io.Serializable {


     private Integer id;
     private Pagina pagina;
     private String nombre;

    public Liga() {
    }

	
    public Liga(Pagina pagina) {
        this.pagina = pagina;
    }
    public Liga(Pagina pagina, String nombre) {
       this.pagina = pagina;
       this.nombre = nombre;
    }
   

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }


    public Pagina getPagina() {
        return this.pagina;
    }
    
    public void setPagina(Pagina pagina) {
        this.pagina = pagina;
    }

    

    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


