package com.tugambeta.model;
// Generated 5/11/2016 06:03:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;


/**
 * Pagina generated by hbm2java
 */

public class Pagina implements java.io.Serializable {

    

    private Integer id;
    private Users users;
    private String nombre;
    private Integer actual;
    private String tipo;
    private String dobles;
    private String triples;

    private Set<Liga> ligas = new HashSet<Liga>(0);

    public Pagina() {
    }

    public Pagina(Users users) {
        this.users = users;
    }


    public Pagina(Users users, String nombre, Integer actual, String tipo, Set<Liga> ligas , String dobles, String triples) {
        this.users = users;
        this.nombre = nombre;
        this.actual = actual;
        this.tipo = tipo;
        this.ligas = ligas;
        this.dobles = dobles;
        this.triples = triples;
    }


    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }


    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }


    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }


    public Integer getActual() {
        return this.actual;
    }

    public void setActual(Integer actual) {
        this.actual = actual;
    }


    public Set<Liga> getLigas() {
        return this.ligas;
    }

    public void setLigas(Set<Liga> ligas) {
        this.ligas = ligas;
    }
    /**
     * @return the dobles
     */

    public String getDobles() {
        return dobles;
    }

    /**
     * @param dobles the dobles to set
     */
    public void setDobles(String dobles) {
        this.dobles = dobles;
    }

    /**
     * @return the triples
     */

    public String getTriples() {
        return triples;
    }

    /**
     * @param triples the triples to set
     */
    public void setTriples(String triples) {
        this.triples = triples;
    }

}
