package com.tugambeta.model;
// Generated 5/11/2016 06:03:56 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Partidos generated by hbm2java
 */
public class Partidos implements java.io.Serializable {

    private Integer idpartidos;
    private Quiniela quiniela;
    private String resultado;
    private String local;
    private String visitante;
    private Integer goleslocal;
    private Integer golesvisita;
    private Set<Jugadorresultados> jugadorresultadoses = new HashSet<Jugadorresultados>(0);

    public Partidos() {
    }

    public Partidos(String local, String visita) {
        this.local = local;
        this.visitante = visita;
    }

    public Partidos(Quiniela quiniela, int golesvisita) {
        this.quiniela = quiniela;
        this.golesvisita = golesvisita;
    }

    public Partidos(Quiniela quiniela, String resultado, String local, String visitante, Integer goleslocal, int golesvisita, Set<Jugadorresultados> jugadorresultadoses) {
        this.quiniela = quiniela;
        this.resultado = resultado;
        this.local = local;
        this.visitante = visitante;
        this.goleslocal = goleslocal;
        this.golesvisita = golesvisita;
        this.jugadorresultadoses = jugadorresultadoses;
    }


    public Integer getIdpartidos() {
        return this.idpartidos;
    }

    public void setIdpartidos(Integer idpartidos) {
        this.idpartidos = idpartidos;
    }
    

    public Quiniela getQuiniela() {
        return this.quiniela;
    }

    public void setQuiniela(Quiniela quiniela) {
        this.quiniela = quiniela;
    }


    public String getResultado() {
        return this.resultado;
    }

    public void setResultado(String resultado) {
        this.resultado = resultado;
    }


    public String getLocal() {
        return this.local;
    }

    public void setLocal(String local) {
        this.local = local;
    }


    public String getVisitante() {
        return this.visitante;
    }

    public void setVisitante(String visitante) {
        this.visitante = visitante;
    }


    public Integer getGoleslocal() {
        return this.goleslocal;
    }

    public void setGoleslocal(Integer goleslocal) {
        this.goleslocal = goleslocal;
    }

    public Integer getGolesvisita() {
        return this.golesvisita;
    }

    public void setGolesvisita(Integer golesvisita) {
        this.golesvisita = golesvisita;
    }


    public Set<Jugadorresultados> getJugadorresultadoses() {
        return this.jugadorresultadoses;
    }

    public void setJugadorresultadoses(Set<Jugadorresultados> jugadorresultadoses) {
        this.jugadorresultadoses = jugadorresultadoses;
    }

}
